### ISSUE TITLE
ImportError: cannot import name 'Type'

### ISSUE THREAD

**Issue by wueching** [leimao/Voice_Converter_CycleGAN#28]
(py35) wueching@ubuntu:~/research/ai/Voice_Converter_CycleGAN$ python convert.py --model_dir ./model/sf1_tm1 --model_name sf1_tm1.ckpt --data_dir ./data/evaluation_all/SF1 --conversion_direction A2B --output_dir ./converted_voices
Traceback (most recent call last):
  File "convert.py", line 6, in <module>
    from preprocess import *
  File "/home/wueching/research/ai/Voice_Converter_CycleGAN/preprocess.py", line 1, in <module>
    import librosa
  File "/home/wueching/anaconda2/envs/py35/lib/python3.5/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/wueching/anaconda2/envs/py35/lib/python3.5/site-packages/librosa/core/__init__.py", line 102, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/wueching/anaconda2/envs/py35/lib/python3.5/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/home/wueching/anaconda2/envs/py35/lib/python3.5/site-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/wueching/anaconda2/envs/py35/lib/python3.5/site-packages/librosa/util/utils.py", line 5, in <module>
    import scipy.ndimage
  File "/home/wueching/anaconda2/envs/py35/lib/python3.5/site-packages/scipy/__init__.py", line 156, in <module>
    from . import fft
  File "/home/wueching/anaconda2/envs/py35/lib/python3.5/site-packages/scipy/fft/__init__.py", line 76, in <module>
    from ._basic import (
  File "/home/wueching/anaconda2/envs/py35/lib/python3.5/site-packages/scipy/fft/_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "/home/wueching/anaconda2/envs/py35/lib/python3.5/site-packages/scipy/_lib/uarray.py", line 27, in <module>
    from ._uarray import *
  File "/home/wueching/anaconda2/envs/py35/lib/python3.5/site-packages/scipy/_lib/_uarray/__init__.py", line 114, in <module>
    from ._backend import *
  File "/home/wueching/anaconda2/envs/py35/lib/python3.5/site-packages/scipy/_lib/_uarray/_backend.py", line 1, in <module>
    from typing import (
ImportError: cannot import name 'Type'

How to fix this problem?Thanks a lot.

**Comment by leimao** [comment]
Please try the container first to see if the problem can be reproduced.

**Comment by wueching** [comment]
(py35) wueching@ubuntu:~/research/ai/Voice_Converter_CycleGAN$ sudo docker build --rm -t tensorflow-cyclegan-vc:1.0 -f Dockerfile .
[sudo] password for wueching: 
Sending build context to Docker daemon 3.235 GB
Sending build context to Docker daemon 
Step 0 : FROM nvcr.io/nvidia/tensorflow:19.09-py3
Pulling repository nvcr.io/nvidia/tensorflow
INFO[0104] Authentication is required.                  
(py35) wueching@ubuntu:~/research/ai/Voice_Converter_CycleGAN$ docker run -it --rm -v $(pwd):/mnt tensorflow-cyclegan-vc:1.0
FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS? 
(py35) wueching@ubuntu:~/research/ai/Voice_Converter_CycleGAN$ sudo docker run -it --rm -v $(pwd):/mnt tensorflow-cyclegan-vc:1.0
Unable to find image 'tensorflow-cyclegan-vc:1.0' locally
Pulling repository tensorflow-cyclegan-vc
FATA[0042] Get https://index.docker.io/v1/repositories/library/tensorflow-cyclegan-vc/images: dial tcp 52.200.232.54:443: connection refused 
@leimao

**Comment by leimao** [comment]
Please build the container first.

**Comment by wueching** [comment]
when build the container,it said "Authentication is required",it seems not generate a image.

**Comment by wueching** [comment]
It can't visit nvcr.io in china.

**Comment by leimao** [comment]
Somehow it might need docker login for some users.
1. Create an account on https://ngc.nvidia.com/
2. Login and follow the instruction on https://ngc.nvidia.com/setup/api-key

**Comment by wueching** [comment]
Docker™ 
For the username, enter '$oauthtoken' exactly as shown. It is a special authentication token for all users.

docker login nvcr.io

Username: $oauthtoken
Password: cG45ajBhZTc1dDF1MGQwbXU0NDRpNXB2ODE6YWRlODM4NmUtNGNiZi00NWM1LWIwMTUtNTMxODMxMzU1ZjNl

API Key generated successfully. This is the only time your API Key will be displayed. Keep your API Key secret.
Do not share it or store it in a place where others can see or copy it.
API Key: cG45ajBhZTc1dDF1MGQwbXU0NDRpNXB2ODE6YWRlODM4NmUtNGNiZi00NWM1LWIwMTUtNTMxODMxMzU1ZjNl

(py35) wueching@ubuntu:~/research/ai/Voice_Converter_CycleGAN$ sudo docker login nvcr.io
Username: wueching
Password: 
Email: wuchengyoung@126.com
FATA[0016] Error response from daemon: </html> 

Created a account,but login failed.

**Comment by wueching** [comment]
(py35) wueching@ubuntu:~/research/ai/Voice_Converter_CycleGAN$ sudo docker login nvcr.io
Username: $oauthtoken
Password: 
Email: wuchengyoung@126.com
FATA[0028] Error response from daemon: </html>

**Comment by wueching** [comment]
I have found the reason,ubuntu in VM can't visit nvidia.com,it shows bellow:
Secure Connection Failed

"The connection to the server was reset while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem."

**Comment by wueching** [comment]
Ubuntu in VM can visit nvidia.com now,but still failed loggin by docker.I don't know how to do now.

**Comment by karkirowle** [comment]
I can confirm on my system that by creating an account and generating the API key this works (Ubuntu 18.04). I have relatively limited experience with Docker, so I cannot judge if this step is trivial. I would advise to add the steps above to the Docker setup in the README.md.
